apiVersion: v1
kind: Secret
metadata:
  name: gutendex-secret
  namespace: ocean
type: Opaque
stringData:
  # Generate with: openssl rand -base64 50
  # Or just use a long random string (50+ characters)
  SECRET_KEY: "RJAH4bgbmaw5USt0GEwdTTDGjssHDfDcQon4rCcQZ2wrOXTM//xDu1B2R2LV2Q/+nAc="
