apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gutendex.fullname" . }}
  labels:
    {{- include "gutendex.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.secretKey | quote }}
